Update bif_upload

diff --git a/bif_upload b/bif_upload
--- a/bif_upload
+++ b/bif_upload
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Exit codes
+# 1 = Script cancelled due to no files.
+
 ### Main Variables ###
 
 new_loc="/mnt/unionfs/bif"
@@ -12,6 +15,15 @@ plex_dir="/opt/plex/Library/Application Support/Plex Media Server/Media/"
 
 arrayRead() {
 readarray -t bifArray < <(fd -e bif index-sd "$plex_dir")
+}
+
+checkExist() {
+if [ ${#bif_array[@]} -eq 0 ]; then
+  echo "$(date "+%d.%m.%Y %T") INFO: There are ${#bif_array[@]} index-sd.bif files currently. Exiting script."
+  exit 1
+else
+  echo "$(date "+%d.%m.%Y %T") INFO: There are currently ${#bif_array[@]} index-sd.bif files. Moving to next step."
+fi
 }
 
 moveCreate() {
@@ -44,6 +56,7 @@ done
 ### Run Functions ###
 
 arrayRead
+checkExist
 moveCreate
 uploadFile
 symlinkCreate
